### ISSUE TITLE
Не подключён STB

### ISSUE THREAD

**Issue by Zhikharev** [Zhikharev/selen#10]
На интерфейсе WBD сигнал stb в Z

**Comment by AlexBolotnikov** [comment]
почему у нас нет stall со стоорны data это не правильно так ? я его добавлю у напишу FSM  для паияти

**Comment by Zhikharev** [comment]
Со стороны WBD у нас нет конвейерных запросов: от ядра может быть активен только один запрос, так как мы имеем in-order ядро. 
На стадии MEM пока не придёт ответ из памяти мы не можем исполнять следующие инструкции.

**Comment by AlexBolotnikov** [comment]
Сделал
