### ISSUE TITLE
Чтение из ROM

### ISSUE THREAD

**Issue by Zhikharev** [Zhikharev/selen#11]
Сейчас в системной сборке процессор начинает отправлять запросы, но они не доходят до ROM и не выставляется сигнал stall -> процессор отправляет запросы до бесконечности.

Нужно исправить коммутатор и блоки периферии.

**Comment by pointhex** [comment]
Я исправил.
Проверил в своем тесте.

**Comment by Zhikharev** [comment]
Проблема не устранена. В ядро не возвращаются ответы и не выставляется stall

**Comment by pointhex** [comment]
Значит буфер не успевает заполняться. Или он обязательно должен
заполняться? Тогда нужно вводить ещё один внешний сигнал РОМ для
управлением rd_en для fifo.
11 дек. 2015 г. 20:19 пользователь "Zhikharev" <notifications@github.com>
написал:

**Comment by Zhikharev** [comment]
Буфер не обязательно должен заполняться, но сомнительно что проблема в этом.
Сколько позиций в буфере?
И это уж точно никак не влияет на то, что ответы не приходят.

**Comment by pointhex** [comment]
А я понял, ответы не возвращаются все же.
Хм, я посмотрю еще раз, но на моем тесте вчера все работало.

12 декабря 2015 г., 11:55 пользователь Zhikharev <notifications@github.com>
написал:

> Буфер не обязательно должен заполняться, но сомнительно что проблема в
> этом.
> Сколько позиций в буфере?
> И это уж точно никак не влияет на то, что ответы не приходят.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Zhikharev/selen/issues/11#issuecomment-164127034>.
>



-- 
 С уважением, Соколовский Артем.

+79629225325

**Comment by Zhikharev** [comment]
Если в твоём тесте была не вся сборка, то тут может быть, что угодно.

**Comment by pointhex** [comment]
Я проверю еще раз и отпишусь.

**Comment by Zhikharev** [comment]
Такими темпами, мы не успеем. Есть ли продвижения тут?

**Comment by pointhex** [comment]
Да продвижения есть.
Я проверил у себя у меня все окей.
Я поставил questasim единственное у меня ругается на то, что не включен режим проверки лицензии. Не подскажете в чем проблема?

**Comment by Zhikharev** [comment]
Какая именно ошибка? Скопируй сюда.
Возможно ты не создал лицензию для своего компьютера.

**Comment by pointhex** [comment]
Я создал, когда запускаю гуй он мне пишет Unable to checkout a viewer license necessary for use of the modelsim graphical user interface. Vsim is closing.

**Comment by Zhikharev** [comment]
А без графического режима запускается? (нужно убрать команду -c)

**Comment by Zhikharev** [comment]
То есть наоборот нужно добавить команду -c в SIM_OPTS например

**Comment by pointhex** [comment]
Ну я запускал просто vsim. И все он сразу в гуй запускает.
В каком файле -с добавить? или в переменных окружения?

**Comment by Zhikharev** [comment]
vsim -novopt -do 'run -all' -c system_tb_top

**Comment by Zhikharev** [comment]
Или воспользоваться наших мэйкфалом:
make -f <путь>/questaMakefile GIT_HOME=<путь к репозиторию> sim SIM_OPTS="-c"

**Comment by pointhex** [comment]
Спасибо!
Я попробую чуть позже и напишу.

**Comment by pointhex** [comment]
Попробовал то, что мне сказали, но безуспешно.

**Comment by pointhex** [comment]
Попробовал поставить все заново но все так же.

**Comment by Zhikharev** [comment]
Что значит безуспешно? 
Скорее всего ты неправильно генерируешь лицензию. 
Указываешь LM_LICENSE_FILE? Следуешь ли инструкции, которая была сделана для установки questasim?

**Comment by pointhex** [comment]
Да все сделал как надо.
LM_LICENSE_FILE добавил.

**Comment by Zhikharev** [comment]
Ну если всё сделал как надо, но то должно работать. 
Если не работает, то опять же: какая ошибка?
