### ISSUE TITLE
SIM, summary

### ISSUE THREAD

**Issue by Zhikharev** [Zhikharev/selen#17]
Было бы круто если б в SUMMARY кроме количества исполненных инструкций так же выводилось количество инструкций обращение  память (возможно нужно будет для статистики). 

Можно даже пойти дальше и выводить статистику по всем инструкциям.

Будет ли у нас такой функционал?

**Comment by Jettatura** [comment]
запросто

**Comment by Jettatura** [comment]
а в каком виде:
```
SUMMARY:
шаг сделано:  200

таблица обращений к  памяти:
тип(чтение/запись)  инструкция(адрес/мнемоника)  адрес обращения   значение
    ...                                    ....                                                  ....                                ....
```

**Comment by Zhikharev** [comment]
Я думаю просто некая статистика 
<code>
код инструкции(мнемоника)     количество 
</code>
