### ISSUE TITLE
RISC5 ISA version

### ISSUE THREAD

**Issue by Zhikharev** [Zhikharev/selen#2]
На какую версию isa мы ориентируемся: v2.0?

**Comment by gipnocow** [comment]
Да, на версию, которая была загружена с аккаунта Болотникова

**Comment by Zhikharev** [comment]
У нас там 36 инструкций, а в официальном документе 47. Как можно это прокомментировать? 
Если на данном этапе мы решили, какие-либо инструкции не реализовывать, то их нужно отметить.

**Comment by AlexBolotnikov** [comment]
Да на 2 версию (там есть все кроме команд для операционной системы)
--
С уважением Александр Болотников Monday, 12 October 2015, 08:04PM +04:00 from Zhikharev < notifications@github.com> :

**Comment by Zhikharev** [comment]
Нужно удалить из репозитория все лишнее файлы с isa, оставить одну конечную

**Comment by Zhikharev** [comment]
Кроме того возник ряд вопрос по действиям в документах, их нужно в тексте подправить:
1) ADD. Что там с переполнением?
2) SLTU. Что за rd2?
3) ADDI. Что такое se? Как рассчитывается?
4) Какие операции совершаются при ветвление (что к чему прибавляется)?
5) В ISA нужно указать имена регистров и переводы сокращений

**Comment by Jettatura** [comment]
Придется отлаживать, работать с этим в чем-нибудь автоматическом 
поэтому:
на первом этапе надо обязательно включать
NOP. ( убирать прыжки, отлаживать) 
что-нибудь вроде  SBREAK, если вдруг мы захотим  знать что у нас выполнение доходит до интересных точек, или до конца.
Без этого сложность написания чего-то что эти инструкции кушает повышается.

**Comment by Jettatura** [comment]
просто я их в ISA_version_2 не увидел, а полного RISC V нам сейчас наверное и не надо.
Отметьте их, пожалуйста.

**Comment by Zhikharev** [comment]
1) По поводу NOP:
The NOP instruction does not change any user-visible state, except for advancing the pc. NOP is encoded as ADDI x0, x0, 0.
2) SBREAK будем думать
