### ISSUE TITLE
Реализация test_api

### ISSUE THREAD

**Issue by Zhikharev** [Zhikharev/selen#28]
Необходимо написать реализацию функций:
https://github.com/Zhikharev/selen/blob/master/verif/system/tests/test_api.h

Если вопросы будут, будем решать их по ходу.

**Comment by Jettatura** [comment]
что должны делать функции print_*?

**Comment by Zhikharev** [comment]
Это нам нужно будет придумать :)
Давай для начала зададимся адресами в ram
