### ISSUE TITLE
Программа для прототипа

### ISSUE THREAD

**Issue by Zhikharev** [Zhikharev/selen#29]
Для запуска прототипа нужна программа, которая будет работать с gpio и моргать лампочкой.
Документация на gpio тут https://github.com/Zhikharev/selen/tree/master/doc/others

**Comment by Zhikharev** [comment]
Алгоритм может быть следующий:
1) настроить 0 пин на вход, настроить параметр события (это будет внешняя кнопка)
2) дождаться события через полинг 
3) настроить 1 пин на выход (это будет лампочка)
4) используя таймер ядра инвертировать значение для пина 1 (мигание)

P. S. Можно на коленке написать, мы бы сразу провели моделирование

**Comment by Jettatura** [comment]
firmware/sandbox/blink.c мои изыскания, предлагай детали

**Comment by Zhikharev** [comment]
Таймер нужно посмотреть привилигированную архитектуру riscv, должны быть специальные системные инструкции.
Кстати умеешь пользоватьс inline ассемблером?

**Comment by Jettatura** [comment]
Понял, умею.

**Comment by Jettatura** [comment]
посмотри пожалуйста, как теперь?
ассемблерный листинг test.s вразумительный получается.
Стартап код?
можно наш простой 
```
la sp, stack_top
 j main
```
или надо что-нибудь поинтереснее?

**Comment by Jettatura** [comment]
добавил скрипт линкера и startup код. Собирается вроде.
