### ISSUE TITLE
Коммутатор

### ISSUE THREAD

**Issue by Zhikharev** [Zhikharev/selen#3]
Информация к размышлению. В целом коммутатор не связан с нашими блоками периферии (iohub, ram, rom) и с ядром. Он просто имеет определённое количество портов. Приоритетность портов и коммутируемость может быть настроена через программной доступные регистры коммутатора встроенным софтом. 
Я не призываю делать универсальный коммутатор сразу, сначала нужно получить готовое решение для наших нужд. Но иметь в виду стоит.

**Comment by pointhex** [comment]
Я так понял, коммутатор должен быть полноценным устройством со своими ригистрами и с несколькими портами для слейвов и несколько для мастеров?
3 слева надо и 3 мастера?

**Comment by Zhikharev** [comment]
Вообще, у полноценного коммутатора все порты должны быть равнозначны, но тут мы делаем конкретную реализацию.
Вопрос терминологии. Если к порту подключено мастер устройство, то порт будем называть мастер-портом. Получается коммутатор может коммутировать данные с мастер порта на слейв порт. 

Предлагаю сигналы коммутатора не привязывать к именам блоков СнК, но создать дополнительную обёртку (дополнительный модуль) с сигналами соответствующими cpu, ram и т.д., внутри которой установить коммутатор и правильно соединить.

**Comment by pointhex** [comment]
Хорошо сделаю обертку. 
А есть смысл делать нормальный коммутатор с 3 мастерами и слейвами? Или пока оставить как есть?

**Comment by Zhikharev** [comment]
Если делать более строго, с определённым количеством слейвов и мастеров, то нужно добавлять программное управление арбитражом и т. п.

**Comment by pointhex** [comment]
Надо будет лично все по точнее обсудить.

**Comment by Zhikharev** [comment]
К субботе готовьте вопросы и варианты решения, в институте обсудим.

**Comment by pointhex** [comment]
Хорошо. Во сколько?
